name: Build and test

on:
  push:
    branches: [ principal ]
  pull_request:
    branches: [ principal ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
    - name: Add private GitHub registry to NuGet
      run: |
        rm -f ./nuget.config
        echo $(sed -e "s/\${USER}/es-wolters-kluwer/" -e "s@\${PAT}@${{ secrets.GITHUB_TOKEN }}@" nuget.config) >nuget.config

    - name: Restore dependencies 
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --framework netcoreapp3.1
